# Generated by Django 6.1.1 on 2026-09-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('my_skills', models.TextField(help_text='Comma-separated skills')),
                ('match_score', models.IntegerField(default=0)),
                ('missing_skills', models.TextField(blank=True)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
